name: ws-pa04
channels:
  - defaults
  - conda-forge
dependencies:
  - scikit-learn==1.3.2
  - gensim==3.7.3
  - nltk==3.8.1
  - regex==2024.4.16
  - tqdm==4.66.2
  - torch==2.3.0
  # - transformers==4.40.1
