import mongoose from "mongoose";

export function makeApiRecord(db) {
    return db.model('ApiRecord', new mongoose.Schema({
        id: {type: String},
        title: {type: String},
        summary: {type: String},
        rating: {type: Number, default: 0.0},
        name: {type: String},
        label: {type: String},
        author: {type: String},
        description: {type: String},
        type: {type: String},
        downloads : {type: Number, default: 0.0},
        useCount : {type: Number, default: 0.0},
        sampleUrl: {type: String},
        downloadUrl : {type: String},
        dateModified: {type: Date},
        remoteFeed : {type: String},
        numComments : {type: Number, default: 0.0},
        commentsUrl: {type: String},
        Tags: [{type: String}],
        category: {type: String},
        protocols: [{type: String}],
        serviceEndpoint: {type: String},
        version : {type: String},
        wsdl : {type: String},
        data_formats: [{type: String}],
        api_groups : [{type: String}],
        example : {type: String},
        clientInstall : {type: String},
        authentication : {type: String},
        ssl : {type: String},
        readonly : {type: String},
        VendorApiKits : [{type: String}],
        CommunityApiKits : [{type: String}],
        blog : {type: String},
        forum : {type: String},
        support : {type: String},
        accountReq: {type: String},
        commercial : {type: String},
        provider: {type: String},
        managedBy : {type: String},
        nonCommercial : {type: String},
        dataLicensing : {type: String},
        fees : {type: String},
        limits : {type: String},
        terms : {type: String},
        company : {type: String},
        updated: {type: Date}
    }));

}